@startuml(id=SystemContext)
title Internet Banking System - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<4>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<5>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<7>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0B4884
}
rectangle "==Personal Banking Customer\n<size:10>[Person]</size>\n\nA customer of the bank, with personal bank accounts." <<1>> as 1
package "Big Bank plc" {
  rectangle "==E-mail System\n<size:10>[Software System]</size>\n\nThe internal Microsoft Exchange e-mail system" <<5>> as 5
  rectangle "==Internet Banking System\n<size:10>[Software System]</size>\n\nAllows customers to view information about their bank accounts, and make payments." <<7>> as 7
  rectangle "==Mainframe Banking System\n<size:10>[Software System]</size>\n\nStores all of the core banking information about customers, accounts, transactions, etc." <<4>> as 4
}
5 .[#707070].> 1 : "Sends e-mails to"
7 .[#707070].> 5 : "Sends e-mail using"
7 .[#707070].> 4 : "Gets account information from, and makes payments using"
1 .[#707070].> 7 : "Views account balances, and makes payments using"
@enduml