@startuml(id=SystemLandscape)
title System Landscape for Big Bank plc

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<2>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<3>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<4>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<5>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<6>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6B6B6B
}
skinparam rectangle<<7>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0B4884
}
rectangle "==Personal Banking Customer\n<size:10>[Person]</size>\n\nA customer of the bank, with personal bank accounts." <<1>> as 1
package "Big Bank plc" {
  rectangle "==Back Office Staff\n<size:10>[Person]</size>\n\nAdministration and support staff within the bank." <<3>> as 3
  rectangle "==Customer Service Staff\n<size:10>[Person]</size>\n\nCustomer service staff within the bank." <<2>> as 2
  rectangle "==ATM\n<size:10>[Software System]</size>\n\nAllows customers to withdraw cash." <<6>> as 6
  rectangle "==E-mail System\n<size:10>[Software System]</size>\n\nThe internal Microsoft Exchange e-mail system" <<5>> as 5
  rectangle "==Internet Banking System\n<size:10>[Software System]</size>\n\nAllows customers to view information about their bank accounts, and make payments." <<7>> as 7
  rectangle "==Mainframe Banking System\n<size:10>[Software System]</size>\n\nStores all of the core banking information about customers, accounts, transactions, etc." <<4>> as 4
}
6 .[#707070].> 4 : "Uses"
3 .[#707070].> 4 : "Uses"
2 .[#707070].> 4 : "Uses"
5 .[#707070].> 1 : "Sends e-mails to"
7 .[#707070].> 5 : "Sends e-mail using"
7 .[#707070].> 4 : "Gets account information from, and makes payments using"
1 .[#707070].> 6 : "Withdraws cash using"
1 .[#707070].> 2 : "Asks questions to\n<size:8>[Telephone]</size>"
1 .[#707070].> 7 : "Views account balances, and makes payments using"
@enduml