# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          java-package: jre
        
      - name: Setup dependencies
        run: sudo apt-get install graphviz wget && wget -O plantuml.jar "https://sourceforge.net/projects/plantuml/files/latest/download"
      
      - name: list dir
        run: ls -l  && cat plantuml.jar
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main_repo
          
      - name: Generate images
        run: java -jar plantuml.jar -o main_repo/images/ "main_repo/*/**.puml"
          
      - name: list dir
        run: ls -l
        
      - name: list dir
        run: |
          pushd main_repo
          ls -l
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"  
          git add -A
          git commit -am "Auto commit after generating images"
          popd
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: main_repo
